# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Ben Chadfield
tagline:          A blog
url:              http://chadfield.org
baseurl:          /

author:
  name:           'Ben Chadfield'
  url:            https://twitter.com/benchadfield

paginate:         5
paginate_path:    "page/:num"

jekyll_timeago:
  depth:          1
  suffix:         'old'

assets:
  js_compressor:  uglifier
  css_compressor: sass

exclude: [Rakefile, CNAME, LICENSE.md, README.md, Gemfile, Gemfile.lock]

gems:
  - jekyll-assets
  - jekyll-paginate